[workspace]
resolver = "3"
members = [
    "app",
    "core",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT"
keywords = []
readme = "README.md"
repository = "https://github.com/cirno-app/cirno"
documentation = "https://docs.rs/cirno"

[workspace.dependencies]
