[package]
name = "cirno"
description = ""
license.workspace = true
keywords.workspace = true
readme.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
anyhow = "1.0.98"
axum = { version = "0.8.4", features = ["http2"] }
clap = { version = "4.5.38", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tao = "0.33.0"
tokio = { version = "1.45.1", features = ["full"] }
wry = "0.51.2"
