[package]
name = "cirno"
description = ""
license.workspace = true
keywords.workspace = true
readme.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
anyhow = "1.0.98"
arc-swap = "1.7.1"
axum = { version = "0.8.4", features = ["http2"] }
clap = { version = "4.5.38", features = ["derive"] }
clap-verbosity-flag = "3.0.3"
env_logger = "0.11.8"
log = { version = "0.4.27", features = ["std"] }
serde = { version = "1.0.219", features = ["derive", "std"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
tao = "0.34.0"
tap = "1.0.1"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
tokio-util = "0.7.16"
wry = "0.52.1"
